name: elepay_flutter
description: elepay SDK wrapper for Flutter
version: 2.0.0
homepage: https://elepay.io

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: io.elepay.sdk.elepay_flutter
        pluginClass: ElepayFlutterPlugin
      ios:
        pluginClass: ElepayFlutterPlugin
